### ISSUE TITLE
Screenshot tests CI job is stalling

### ISSUE THREAD

**Issue by mattab** [PiwikPRO/plugin-InterSites#11]
I tried to restart the job but it stalled again. Any idea what could cause this issue?

```
CompareCommonVisitors

    Setting up fixture Piwik\Plugins\InterSites\Tests\Fixtures\ThreeSitesWithSharedVisitors...

    Database InterSites_ThreeSitesWithSharedVisitors marked as successfully set up.

    

    *******************************

      Fixture successfully setup!  

    *******************************

    

    

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.


```

**Comment by sebastianpiskorski** [comment]
I've tried locally to do the simplest UI test on this plugin. And it is still stalling.

```javascript
    it("should load correctly", function (done) {
        expect.screenshot('loaded').to.be.capture( function (page) {
            page.load("");
        }, done);
    });
```

Looks like `done()` function is never reached. If I've tried to call it in some other places tests reached end, but with corrupted screenshots. 

I have also ran these tests for several different fixtures and effect was the same, test stalling.

**Comment by mattab** [comment]
It seems the build is not stalling anymore, but is broken for other reasons. closing, feel free to open new issues if you need further help :+1:
