### ISSUE TITLE
Bug? Wrong behaviour with day period.

### ISSUE THREAD

**Issue by pestevao** [PiwikPRO/plugin-InterSites#9]
If you select only a day the select query make a request based on visit_last_action_time >= '2015-04-10' AND visit_last_action_time <= '2015-04-10' wich didn't work where (maybe because these fields in the database are datetime type).

The "solution" was to transform the dates by hand to make the select query based on visit_last_action_time >= '2015-04-10 00:00:00' AND visit_last_action_time <= '2015-04-10 23:59:59'.

Before this change the plugin only display data for periods other then a day. Now it works fine for all periods.

Is this a bug?

**Comment by sebastianpiskorski** [comment]
@pestevao  This should be fixed in 0.2.2 which means in current version

**Comment by diosmosis** [comment]
Closing since this is fixed.
